#pragma once

#include <string>

namespace JaroViewer {
	const std::string shaderVersion = "#version 460 core\n";

	const std::string vertexInputs =
	  "layout(std140, binding = 0) uniform Transformation {\n"
	  "mat4 projection;\n"
	  "mat4 view;\n"
	  "};\n"
	  "uniform samplerBuffer modifierData;\n"
	  "layout (location = 0) in vec3 aPos;\n"
	  "layout (location = 1) in vec3 aNormal;\n"
	  "layout (location = 2) in vec2 aTexCoord;\n"
	  "layout (location = 3) in mat4 aModel;\n"
	  "layout (location = 7) in mat3 aNormalModel;\n"
	  "layout (location = 10) in uint aModifierStart;\n"
	  "layout (location = 11) in uint aModifierCount;\n";

	const std::string basicWhiteVertex = shaderVersion + vertexInputs +
	  "vec4 transform(vec3 pos) {\n"
	  "return projection * view * aModel * vec4(pos, 1.0);\n"
	  "}\n"
	  "void main() {\n"
	  "gl_Position = transform(aPos);\n"
	  "}\n";

	const std::string basicWhiteFragment = shaderVersion +
	  "out vec4 FragColor;\n"
	  "void main() {\n"
	  "FragColor = vec4(1.0);\n"
	  "}\n";

	const std::string vertexLibrary = shaderVersion + vertexInputs +
	  "vec4 transform(vec3 pos) {\n"
	  "return projection * view * aModel * vec4(pos, 1.0);\n"
	  "}\n"
	  "float getDataFromVector(samplerBuffer vec, int index) {\n"
	  "return texelFetch(vec, index).r;\n"
	  "}\n";

	const std::string fragmentLibrary = shaderVersion +
	  "#define MAXNUMDIRLIGHTS 2\n"
	  "#define MAXNUMPOINTLIGHTS 20\n"
	  "#define MAXNUMSPOTLIGHTS 10\n"
	  "struct Material {\n"
	  "sampler2D diffuse;\n"
	  "sampler2D specular;\n"
	  "float shininess;\n"
	  "};\n"
	  "struct LightPosSet {\n"
	  "vec3 normal;\n"
	  "vec3 fragPos;\n"
	  "vec3 viewPos;\n"
	  "};\n"
	  "struct DirectionalLight {\n"
	  "vec3 direction;\n"
	  "int enable;\n"
	  "vec3 ambient;\n"
	  "vec3 diffuse;\n"
	  "vec3 specular;\n"
	  "};\n"
	  "struct PointLight {\n"
	  "vec3 position;\n"
	  "int enable;\n"
	  "vec3 ambient;\n"
	  "float constant;\n"
	  "vec3 diffuse;\n"
	  "float linear;\n"
	  "vec3 specular;\n"
	  "float quadratic;\n"
	  "};\n"
	  "struct Spotlight {\n"
	  "vec3 position;\n"
	  "float cutOff;\n"
	  "vec3 direction;\n"
	  "float outerCutOff;\n"
	  "vec3 ambient;\n"
	  "float constant;\n"
	  "vec3 diffuse;\n"
	  "float linear;\n"
	  "vec3 specular;\n"
	  "float quadratic;\n"
	  "int enable;\n"
	  "};\n"
	  "layout(std140, binding = 1) uniform LightSet {\n"
	  "DirectionalLight dirLights[MAXNUMDIRLIGHTS];\n"
	  "PointLight pointLights[MAXNUMPOINTLIGHTS];\n"
	  "Spotlight spotlights[MAXNUMSPOTLIGHTS];\n"
	  "int numDirLights;\n"
	  "int numPointLights;\n"
	  "int numSpotlights;\n"
	  "}\n"
	  "lightSet;\n"
	  "vec3 calculateAmbient(vec3 ambLight, vec3 fragColor) {\n"
	  "return ambLight * fragColor;\n"
	  "}\n"
	  "vec3 calculateDiffuse(vec3 diffLight, vec3 fragColor, vec3 normal, vec3 "
	  "lightDir) {\n"
	  "float diff = max(dot(normal, lightDir), 0.0);\n"
	  "return diffLight * (diff * fragColor);\n"
	  "}\n"
	  "vec3 calculateSpecular(vec3 specLight, vec3 fragColor, float shininess, "
	  "vec3 normal, vec3 lightDir, vec3 viewDir) {\n"
	  "vec3 halfwayDir = normalize(lightDir + viewDir);\n"
	  "float spec      = pow(max(dot(normal, halfwayDir), 0.0), shininess);\n"
	  "return specLight * (spec * fragColor);\n"
	  "}\n"
	  "vec3 calculateDirectionLight(DirectionalLight light, Material mat, vec2 "
	  "texCoords, LightPosSet posSet) {\n"
	  "if (light.enable == 0) return vec3(0.0);\n"
	  "vec3 norm          = normalize(posSet.normal);\n"
	  "vec3 lightDir      = normalize(light.direction);\n"
	  "vec3 viewDir       = normalize(posSet.viewPos - posSet.fragPos);\n"
	  "vec3 diffuseColor  = vec3(texture(mat.diffuse, texCoords));\n"
	  "vec3 specularColor = vec3(texture(mat.specular, texCoords));\n"
	  "vec3 ambient       = calculateAmbient(light.ambient, diffuseColor);\n"
	  "vec3 diffuse = calculateDiffuse(light.diffuse, diffuseColor, norm, "
	  "-lightDir);\n"
	  "vec3 specular =\n"
	  "calculateSpecular(light.specular, specularColor, mat.shininess, norm, "
	  "-lightDir, viewDir);\n"
	  "return ambient + diffuse + specular;\n"
	  "}\n"
	  "vec3 calculatePointLight(PointLight light, Material mat, vec2 texCoords, "
	  "LightPosSet posSet) {\n"
	  "if (light.enable == 0) return vec3(0.0);\n"
	  "vec3 norm          = normalize(posSet.normal);\n"
	  "vec3 lightDir      = normalize(light.position - posSet.fragPos);\n"
	  "vec3 viewDir       = normalize(posSet.viewPos - posSet.fragPos);\n"
	  "vec3 diffuseColor  = vec3(texture(mat.diffuse, texCoords));\n"
	  "vec3 specularColor = vec3(texture(mat.specular, texCoords));\n"
	  "vec3 ambient       = calculateAmbient(light.ambient, diffuseColor);\n"
	  "vec3 diffuse = calculateDiffuse(light.diffuse, diffuseColor, norm, "
	  "lightDir);\n"
	  "vec3 specular =\n"
	  "calculateSpecular(light.specular, specularColor, mat.shininess, norm, "
	  "lightDir, viewDir);\n"
	  "float distance    = length(light.position - posSet.fragPos);\n"
	  "float attenuation = 1.0 /\n"
	  "(light.constant + light.linear * distance + light.quadratic * (distance * "
	  "distance));\n"
	  "return attenuation * (ambient + diffuse + specular);\n"
	  "}\n"
	  "vec3 calculateSpotlight(Spotlight light, Material mat, vec2 texCoords, "
	  "LightPosSet posSet) {\n"
	  "if (light.enable == 0) return vec3(0.0);\n"
	  "vec3 norm     = normalize(posSet.normal);\n"
	  "vec3 lightDir = normalize(light.position - posSet.fragPos);\n"
	  "vec3 viewDir  = normalize(posSet.viewPos - posSet.fragPos);\n"
	  "float theta   = dot(lightDir, normalize(-light.direction));\n"
	  "if (theta < light.outerCutOff) return vec3(0.0f);\n"
	  "float epsilon      = light.cutOff - light.outerCutOff;\n"
	  "float intensity    = clamp((theta - light.outerCutOff) / epsilon, 0.0, "
	  "1.0);\n"
	  "vec3 diffuseColor  = vec3(texture(mat.diffuse, texCoords));\n"
	  "vec3 specularColor = vec3(texture(mat.specular, texCoords));\n"
	  "vec3 ambient       = calculateAmbient(light.ambient, diffuseColor);\n"
	  "vec3 diffuse = calculateDiffuse(light.diffuse, diffuseColor, norm, "
	  "lightDir);\n"
	  "vec3 specular =\n"
	  "calculateSpecular(light.specular, specularColor, mat.shininess, norm, "
	  "lightDir, viewDir);\n"
	  "float distance    = length(light.position - posSet.fragPos);\n"
	  "float attenuation = 1.0 /\n"
	  "(light.constant + light.linear * distance + light.quadratic * (distance * "
	  "distance));\n"
	  "return intensity * attenuation * (ambient + diffuse + specular);\n"
	  "}\n"
	  "vec4 getLightCorrectedColor(Material mat, vec2 texCoords, LightPosSet "
	  "posSet) {\n"
	  "vec3 result = vec3(0.0);\n"
	  "for (int i = 0; i < lightSet.numDirLights; i++)\n"
	  "result += calculateDirectionLight(lightSet.dirLights[i], mat, texCoords, "
	  "posSet);\n"
	  "for (int i = 0; i < lightSet.numPointLights; i++)\n"
	  "result += calculatePointLight(lightSet.pointLights[i], mat, texCoords, "
	  "posSet);\n"
	  "for (int i = 0; i < lightSet.numSpotlights; i++)\n"
	  "result += calculateSpotlight(lightSet.spotlights[i], mat, texCoords, "
	  "posSet);\n"
	  "return vec4(result, 1.0);\n"
	  "}\n"
	  "uniform Material materials[32];\n"
	  "uniform int numTextures;\n"
	  "uniform vec3 viewPos;\n"
	  "out vec4 FragColor;\n";

	const std::string basicVertex =
	  "out vec2 TexCoord;\n"
	  "out vec3 FragPos;\n"
	  "out vec3 Normal;\n"
	  "void main() {\n"
	  "gl_Position = transform(aPos);\n"
	  "TexCoord    = aTexCoord;\n"
	  "FragPos     = vec3(aModel * vec4(aPos, 1.0));\n"
	  "Normal      = aNormalModel * aNormal;\n"
	  "}\n";

	const std::string basicFragment =
	  "in vec2 TexCoord;\n"
	  "in vec3 FragPos;\n"
	  "in vec3 Normal;\n"
	  "void main() {\n"
	  "LightPosSet posSet = LightPosSet(\n"
	  "Normal,\n"
	  "FragPos,\n"
	  "viewPos\n"
	  ");\n"
	  "FragColor = getLightCorrectedColor(materials[0], TexCoord, posSet);\n"
	  "}\n";

} // namespace JaroViewer
